import {test} from 'node:test';
import assert from 'node:assert/strict';
import {PGlite} from '@electric-sql/pglite';
import {readFileSync} from 'node:fs';
const db=new PGlite();
const patient='00000000-0000-0000-0000-000000000001',other='00000000-0000-0000-0000-000000000002',admin='00000000-0000-0000-0000-000000000003',guest='00000000-0000-0000-0000-000000000004';
await db.exec(`CREATE ROLE anon;CREATE ROLE authenticated;CREATE SCHEMA auth;CREATE SCHEMA private;
CREATE FUNCTION auth.uid() RETURNS uuid LANGUAGE sql STABLE AS $$ SELECT nullif(current_setting('request.user',true),'')::uuid $$;
CREATE FUNCTION auth.jwt() RETURNS jsonb LANGUAGE sql STABLE AS $$ SELECT jsonb_build_object('aal',current_setting('request.aal',true)) $$;
CREATE TABLE auth.users(id uuid PRIMARY KEY,email_confirmed_at timestamptz,raw_user_meta_data jsonb);
CREATE TABLE profiles(id uuid PRIMARY KEY REFERENCES auth.users(id),account_type text);
CREATE FUNCTION private.current_user_is_admin() RETURNS boolean LANGUAGE sql STABLE SECURITY DEFINER AS $$ SELECT EXISTS(SELECT 1 FROM public.profiles WHERE id=auth.uid() AND account_type='admin') $$;
CREATE FUNCTION private.prevent_profile_role_escalation() RETURNS trigger LANGUAGE plpgsql AS $$ BEGIN RETURN NEW;END $$;
CREATE TRIGGER prevent_role BEFORE UPDATE OF account_type ON profiles FOR EACH ROW EXECUTE FUNCTION private.prevent_profile_role_escalation();
CREATE TABLE appointments(id uuid);
GRANT USAGE ON SCHEMA public,auth,private TO authenticated,anon;GRANT SELECT,UPDATE ON profiles TO authenticated;
`);
await db.exec(readFileSync(new URL('../supabase/migrations/20260927024746_patient_registration_intake.sql',import.meta.url),'utf8'));
for(const [id,role] of [[patient,'guest'],[other,'patient'],[admin,'admin'],[guest,'guest']]){await db.query('INSERT INTO auth.users VALUES($1,null,$2)',[id,{registration_type:id===patient?'patient':'guest'}]);await db.query('INSERT INTO profiles VALUES($1,$2)',[id,role]);}
const as=async(id,aal='aal2')=>{await db.exec('RESET ROLE');await db.query("SELECT set_config('request.user',$1,false),set_config('request.aal',$2,false)",[id,aal]);await db.exec('SET ROLE authenticated');};
const q=(sql,args=[])=>db.query(sql,args);
const answers={full_name:'Synthetic Patient',date_of_birth:'1990-01-01',address:'123 Example',city:'Example',state:'KS',postal_code:'66000',phone:'555-0100',email:'test@example.com',insurance_coverage:'unsure',counseling_reason:'Synthetic test only',deductible:'I don’t know'};
await test('unverified email cannot activate Patient',async()=>{await as(patient);await assert.rejects(q('select complete_registration()'),/Verify your email/);await assert.rejects(q("update profiles set account_type='patient' where id=$1",[patient]),/Account type/);});
await test('verified signup request activates once and cannot grant admin',async()=>{await db.exec('RESET ROLE; UPDATE auth.users SET email_confirmed_at=now()');await as(patient);assert.equal((await q('select complete_registration() role')).rows[0].role,'patient');await assert.rejects(q("update profiles set account_type='admin' where id=$1",[patient]),/Account type/);assert.equal((await q('select complete_registration() role')).rows[0].role,'patient');});
await test('editing metadata later cannot turn Guest into Patient',async()=>{await db.exec('RESET ROLE');await q("update auth.users set raw_user_meta_data='{"+'"registration_type":"patient"'+"}' where id=$1",[guest]);await as(guest);assert.equal((await q('select complete_registration() role')).rows[0].role,'guest');});
await test('patient needs second factor for intake read and writes',async()=>{await as(patient,'aal1');await assert.rejects(q('insert into patient_intakes(patient_id,answers) values($1,$2)',[patient,answers]),/row-level security/);assert.equal((await q('select * from patient_intakes')).rows.length,0);});
await test('secure patient can save draft and cannot write another patient',async()=>{await as(patient);await q('insert into patient_intakes(patient_id,answers) values($1,$2)',[patient,{full_name:'Draft'}]);await assert.rejects(q('insert into patient_intakes(patient_id,answers) values($1,$2)',[other,answers]),/row-level security/);assert.equal((await q('select * from patient_intakes')).rows.length,1);});
await test('other patient, guest and insecure admin cannot read intake',async()=>{for(const [id,aal] of [[other,'aal2'],[guest,'aal2'],[admin,'aal1']]){await as(id,aal);assert.equal((await q('select * from patient_intakes')).rows.length,0);}});
await test('invalid payload and missing required values cannot submit via direct API',async()=>{await as(patient);await assert.rejects(q("update patient_intakes set status='submitted'"),/required/);await assert.rejects(q('update patient_intakes set answers=$1',[{...answers,coinsurance:'101'}]),/coinsurance/);await assert.rejects(q('update patient_intakes set answers=$1',[{...answers,admin:'true'}]),/Invalid intake field/);});
await test('stale draft update matches zero rows; version is server owned',async()=>{await as(patient);await q("update patient_intakes set answers=$1 where version=1",[answers]);assert.equal((await q('select version from patient_intakes')).rows[0].version,2);assert.equal((await q('update patient_intakes set answers=$1 where version=1 returning patient_id',[{}])).rows.length,0);await assert.rejects(q('update patient_intakes set version=1'),/permission denied/);});
await test('submission is immutable and secure admin can review',async()=>{await as(patient);await q("update patient_intakes set status='submitted'");assert.equal((await q("update patient_intakes set answers='{}' returning patient_id")).rows.length,0);await as(admin);assert.equal((await q('select * from patient_intakes')).rows.length,1);assert.equal((await q("update patient_intakes set answers='{}' returning patient_id")).rows.length,0);});
await test('anonymous cannot read or call activation',async()=>{await db.exec('RESET ROLE;SET ROLE anon');await assert.rejects(q('select * from patient_intakes'),/permission denied/);await assert.rejects(q('select complete_registration()'),/permission denied/);});
await db.close();
