// @vitest-environment node
import {afterEach,expect,test,vi} from 'vitest';
import {POST} from '../app/api/omnicore-operation-test/route';
const input={sessionId:'11111111-1111-4111-8111-111111111111',operationId:'22222222-2222-4222-8222-222222222222',operation:'read',record:'alpha',destination:'none'};
const request=(body:unknown=input)=>new Request('https://www.indiancreekpsych.com/api/omnicore-operation-test',{method:'POST',headers:{'content-type':'application/json'},body:JSON.stringify(body)});
function enabled(){vi.stubEnv('OMNICORE_OPERATION_TEST_UNTIL',new Date(Date.now()+60000).toISOString());vi.stubEnv('OMNICORE_INGEST_KEY','synthetic');vi.stubEnv('OMNICORE_SITE_ID',input.sessionId);}
afterEach(()=>{vi.unstubAllEnvs();vi.unstubAllGlobals();vi.restoreAllMocks();});
test('disabled and expired diagnostics return 404 before network activity',async()=>{const fetch=vi.fn();vi.stubGlobal('fetch',fetch);vi.stubEnv('OMNICORE_OPERATION_TEST_UNTIL','');expect((await POST(request())).status).toBe(404);vi.stubEnv('OMNICORE_OPERATION_TEST_UNTIL',new Date(Date.now()-1000).toISOString());expect((await POST(request())).status).toBe(404);expect(fetch).not.toHaveBeenCalled();});
test('denial never exports, forged fields and URL destinations are rejected',async()=>{enabled();const fetch=vi.fn().mockResolvedValue(Response.json({allowed:false,reason:'RECORD_NOT_AUTHORIZED'},{status:403}));vi.stubGlobal('fetch',fetch);expect((await POST(request({...input,operation:'export',destination:'approved',record:'beta'}))).status).toBe(403);expect(fetch).toHaveBeenCalledTimes(1);expect((await POST(request({...input,permissionVerified:true}))).status).toBe(422);expect((await POST(request({...input,operation:'export',destination:'https://example.invalid'}))).status).toBe(422);expect(fetch).toHaveBeenCalledTimes(1);});
test('export requires a verified receipt and sends only fixed synthetic data to fixed upstream',async()=>{enabled();vi.spyOn(console,'info').mockImplementation(()=>{});const fetch=vi.fn().mockResolvedValueOnce(Response.json({allowed:true,value:'SYNTHETIC_ALPHA',operationId:input.operationId})).mockResolvedValueOnce(Response.json({allowed:true,received:true,operationId:input.operationId}));vi.stubGlobal('fetch',fetch);expect((await POST(request({...input,operation:'export',destination:'approved'}))).status).toBe(200);expect(fetch).toHaveBeenCalledTimes(2);expect(fetch.mock.calls.every(c=>c[0]==='https://omnicoreai.app/api/omnicore/monitoring/operation-test')).toBe(true);expect(JSON.parse(fetch.mock.calls[1][1].body)).toMatchObject({operation:'receipt',value:'SYNTHETIC_ALPHA'});});
test('upstream failure is fail closed, no success or second call',async()=>{enabled();const fetch=vi.fn().mockRejectedValue(new Error('offline'));vi.stubGlobal('fetch',fetch);expect((await POST(request({...input,operation:'export',destination:'approved'}))).status).toBe(503);expect(fetch).toHaveBeenCalledTimes(1);});
