import Image from "next/image";
import Link from "next/link";
import { notFound } from "next/navigation";
import PublicHeader from "../../components/PublicHeader";
import PublicFooter from "../../components/PublicFooter";

const specialties = {
 anxiety:{title:"Anxiety",intro:"Anxiety can affect sleep, concentration, relationships, physical comfort, decision-making, and the ability to feel present in everyday life.",points:["Clarify triggers, avoidance patterns, physical arousal, and the beliefs that keep anxiety active.","Develop practical skills for regulation, coping, exposure, problem-solving, and more flexible responding.","Address overlapping concerns such as trauma, depression, ADHD, substance use, or chronic stress when relevant."]},
 depression:{title:"Depression & Mood Disorders",intro:"Mood problems can narrow a person&apos;s world gradually, affecting motivation, energy, sleep, relationships, confidence, and hope.",points:["Assess the pattern, duration, severity, and functional impact of mood symptoms.","Use evidence-informed strategies to improve activation, regulation, routines, problem-solving, and relationships.","Coordinate with medical or psychiatric care when medication evaluation or additional assessment may be useful."]},
 "trauma-ptsd":{title:"Trauma & PTSD",intro:"Trauma can affect safety, memory, emotion, relationships, sleep, concentration, and the nervous system long after an event has ended.",points:["Safety, stabilization, pacing, and informed choice come first.","Treatment may include trauma-focused approaches such as EMDR when clinically appropriate.","The goal is to reduce the degree to which the past controls present-day choices, relationships, and emotional responses."]},
 "substance-use-recovery":{title:"Substance Use & Recovery",intro:"Substance use often becomes intertwined with stress, trauma, mood, relationships, health, identity, and coping.",points:["Understand patterns of use, triggers, consequences, motivation, strengths, and recovery history.","Build practical relapse-prevention, emotional-regulation, decision-making, and support strategies.","Coordinate with medical care, medication-assisted treatment, peer recovery, or higher levels of care when appropriate."]},
 adhd:{title:"ADHD",intro:"ADHD can affect attention, activation, time awareness, working memory, organization, impulse control, emotional regulation, and follow-through.",points:["Identify the individual executive-function pattern rather than relying on generic productivity advice.","Build external systems that reduce dependence on memory, crisis, and willpower.","Address the accumulated frustration, shame, relationship strain, or anxiety that can develop around chronic inconsistency."]},
 autism:{title:"Autism",intro:"Autistic people vary enormously in strengths, communication, sensory profiles, relationships, support needs, and day-to-day challenges.",points:["Use a neurodiversity-informed approach focused on quality of life rather than masking or conformity.","Address anxiety, burnout, trauma, relationships, identity, stress, executive functioning, and communication as relevant.","Adapt treatment to the individual&apos;s communication style, processing pace, sensory needs, and preferences."]},
 "relationship-issues":{title:"Relationship Issues",intro:"Relationship distress is often maintained by patterns rather than by a single argument or a single person.",points:["Identify pursue-withdraw, escalation, avoidance, trust, or boundary patterns.","Improve communication, repair, emotional safety, and clarity around expectations.","Address the effects of trauma, mood, ADHD, substance use, parenting, or major life changes on relationships."]},
 "stress-management":{title:"Stress Management",intro:"Chronic stress can affect the body, attention, mood, sleep, relationships, and the ability to make clear decisions.",points:["Identify the sources of overload and the patterns that keep the nervous system activated.","Develop practical regulation, boundary, pacing, sleep, and problem-solving strategies.","Build a more sustainable balance between responsibilities, recovery, connection, and personal needs."]},
 "life-transitions":{title:"Life Transitions",intro:"Major changes can disrupt identity, routines, relationships, expectations, and a person&apos;s sense of direction.",points:["Make room for grief, uncertainty, and mixed emotions without losing forward movement.","Clarify values, priorities, roles, and realistic next steps.","Build flexibility and confidence during changes in work, relationships, family, health, or life stage."]},
} as const;

export function generateStaticParams(){return Object.keys(specialties).map(slug=>({slug}));}

export default async function SpecialtyDetail({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const s=specialties[slug as keyof typeof specialties]; if(!s)notFound();
 return <div className="publicSite"><PublicHeader/><main>
  <section className="mockHero specialtyDetailHero"><Image className="heroLogoOverlay" src="/images/indian-creek-logo.webp" alt="Indian Creek Psychological Services" width={620} height={240} priority/><div className="heroScrim compact"><p className="eyebrow">Area of specialization</p><h1>{s.title}</h1><p>{s.intro}</p><div className="heroActions"><Link className="primaryButton" href="/appointments">Schedule an Appointment</Link><Link className="secondaryButton" href="/specialties">Back to Specialties</Link></div></div></section>
  <section className="detailTextGrid">{s.points.map((p,i)=><article key={p}><span>{String(i+1).padStart(2,"0")}</span><p>{p}</p></article>)}</section>
  <section className="detailNote"><h2>Specialization is not a substitute for assessment.</h2><p>These pages describe common concerns and treatment considerations. Individual recommendations require a clinical evaluation that considers symptoms, history, goals, strengths, risks, and circumstances.</p></section>
 </main><PublicFooter/></div>
}
