import Link from "next/link";
import { notFound } from "next/navigation";
import PublicHeader from "../../components/PublicHeader";
import PublicFooter from "../../components/PublicFooter";

const services = {
 "individual-therapy":{title:"Individual Therapy",eyebrow:"One-to-one counseling",intro:"Individual therapy provides a confidential setting to understand what is happening, clarify goals, develop practical skills, and create meaningful change.",points:["Treatment is individualized rather than reduced to a diagnosis.","Work may address mood, anxiety, trauma, recovery, relationships, stress, identity, or life transitions.","The therapeutic relationship is collaborative, with clear goals and practical application between sessions."]},
 "couples-therapy":{title:"Couples Therapy",eyebrow:"Relationships",intro:"Couples therapy helps partners understand the patterns beneath recurring conflict and build healthier communication, connection, trust, and repair.",points:["Identify cycles that keep arguments repeating.","Improve listening, emotional safety, boundaries, and clearer requests.","Address the effects of stress, trauma, ADHD, substance use, parenting, or major transitions on the relationship."]},
 "family-therapy":{title:"Family Therapy",eyebrow:"Family systems",intro:"Family therapy looks at how individual symptoms and relationship patterns interact across the family system.",points:["Clarify roles, boundaries, expectations, and communication.","Reduce cycles of escalation, withdrawal, or misunderstanding.","Support families coping with mental health, neurodevelopmental, recovery, or transition-related concerns."]},
 "psychological-assessment":{title:"Psychological Assessment",eyebrow:"Evaluation",intro:"Psychological assessment can help clarify symptoms, strengths, patterns, and treatment needs when the clinical picture is complex or uncertain.",points:["Assessment begins with the referral question and relevant history.","Methods may include interviews, questionnaires, standardized measures, and record review when appropriate.","Results should lead to practical recommendations and a clearer understanding of next steps."]},
 "consultation-services":{title:"Consultation Services",eyebrow:"Professional consultation",intro:"Consultation provides focused clinical perspective for individuals, families, and other professionals facing complex behavioral-health questions.",points:["Clarify the problem and the decision that needs to be made.","Review relevant history, patterns, risks, strengths, and available options.","Develop practical recommendations while remaining within appropriate professional scope."]},
 "telehealth-services":{title:"Telehealth Services",eyebrow:"Secure remote care",intro:"Telehealth can make high-quality psychological care more accessible when remote treatment is clinically appropriate and permitted by licensure and jurisdiction.",points:["Sessions are conducted through an approved secure platform.","Privacy, emergency planning, and the client&apos;s physical location are important parts of telehealth practice.","Some concerns or situations may be better served by in-person care or a higher level of treatment."]},
 "emdr":{title:"EMDR Therapy",eyebrow:"Trauma-focused treatment",intro:"Eye Movement Desensitization and Reprocessing (EMDR) is a structured psychotherapy used most prominently for trauma and PTSD.",points:["EMDR includes assessment, preparation, processing, closure, and reevaluation—not simply eye movements.","During processing, the client briefly attends to aspects of a distressing memory while using bilateral stimulation.","The goal is not to erase memory but to reduce the degree to which the past continues to drive present-day distress and reactions."]},
 "hypnotherapy":{title:"Clinical Hypnotherapy",eyebrow:"Focused-attention therapy",intro:"Clinical hypnosis uses focused attention, absorption, imagery, and therapeutic suggestion to support specific treatment goals.",points:["You remain aware and retain control during hypnosis.","Hypnosis may be used as an adjunct for selected concerns such as stress, anxiety, pain, habits, or behavior change.","It should be used with appropriate assessment, informed consent, and realistic expectations."]},
 "neurofeedback":{title:"Neurofeedback Therapy",eyebrow:"Computerized EEG biofeedback",intro:"Neurofeedback uses real-time information about brain activity to support practice in self-regulation. Indian Creek uses a computerized Brain-Trainer interface.",points:["Scalp sensors read EEG activity; they do not put electricity into the brain.","The computer translates selected physiological information into visual or auditory feedback during training.","Neurofeedback is used as one possible component of an individualized treatment plan and is not presented as a guaranteed cure."]},
} as const;

export function generateStaticParams(){return Object.keys(services).map(slug=>({slug}));}

export default async function ServiceDetail({params}:{params:Promise<{slug:string}>}){
 const {slug}=await params; const s=services[slug as keyof typeof services]; if(!s)notFound();
 return <div className="publicSite"><PublicHeader/><main>
  <section className={`mockHero serviceDetailHero serviceHero-${slug}`}><div className="heroScrim compact"><p className="eyebrow">{s.eyebrow}</p><h1>{s.title}</h1><p>{s.intro}</p><div className="heroActions"><Link className="primaryButton" href="/appointments">Schedule an Appointment</Link><Link className="secondaryButton" href="/services">Back to Our Services</Link></div></div></section>
  <section className="detailTextGrid">{s.points.map((p,i)=><article key={p}><span>{String(i+1).padStart(2,"0")}</span><p>{p}</p></article>)}</section>
  <section className="detailNote"><h2>Individualized care matters.</h2><p>Information on this page is educational and does not establish a diagnosis or treatment recommendation. Appropriate care depends on clinical assessment, goals, history, risks, strengths, and circumstances.</p></section>
 </main><PublicFooter/></div>
}
